[package]
name = "BE"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["full"] }
jsonwebtoken = "9.3"
serde = {version = "1.0", features = ["derive"] }
axum-extra = "0.10.1"
